### ISSUE TITLE
Can not find query id

### ISSUE THREAD

**Issue by santwijaya** [mineur/instagram-parser#4]
I've try installation step for getting query_id. I found that in my console there is no query_id instead query_hash. Any solution for this?

**Comment by alexhoma** [comment]
Hi @santwijaya, thanks for submitting this issue!

Instagram API has changed some things these days. I see that now accepts either `query_id` or `hash_id`, since I've get the following error:
```shell
{"message": "Must provide valid one of: query_id, query_hash", "status": "fail"}
```

I'll updated the library to `query_hash` since there is no way to get `query_id` from the browser now. Also updated the docs on how to get the query hash.
Can you test if it's working now?  Also a star support will be welcome :)

> Note that the symfony bundle isn't still updated to the new version of this library.
